### 데이터 분석을 위한 기본적인 numpy 예제를 알아봅시다.

# 1. Numpy 사용하기

In [1]:
!pip install numpy

In [2]:
import numpy as np

## 2.Numpy 배열
numpy 배열은 데이터분석에서 가장 많이 사용되는 배열 중 하나
* 벡터 : 1차원 배열
* 매트릭스 : 2차원 배열

## 3. 배열 생성하기
1. 파이썬 리스트 이용 : np.array([list])
2. 0 또는 1로 채우기 : np.zeros(), np.ones()
3. 일정한 간격을 가지는 숫자배열 : np.arange()
4. 일정 범위 안에서 일정 갯수를 가진 배열 np.linspace()
5. 랜덤 값을 가지는 배열 : np.random.rand() / randint() / randn()

np.array()

In [4]:
list_array = [1, 2, 3, 4, 5]
type(list_array)
list_array

[1, 2, 3, 4, 5]

In [5]:
len(list_array)

5

In [6]:
arr = np.array(list_array)
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

1

In [9]:
arr.size

5

In [10]:
mat = [[1,2],[3,4]]
mat

[[1, 2], [3, 4]]

In [11]:
m_arr = np.array(mat)
m_arr

array([[1, 2],
       [3, 4]])

In [12]:
m_arr.ndim

2

In [13]:
m_arr.size

4

np.zeros() / np.ones()

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
type(np.zeros(5))

numpy.ndarray

In [17]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

np.arange()

In [20]:
range(11)

range(0, 11)

In [21]:
temp_list = list(range(10))
temp_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
temp_list + 7

TypeError: ignored

In [24]:
np.arange(0,13) + 7

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [27]:
np.arange(0,11,2).reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [29]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

np.random.rand() / randint() / randn()

In [30]:
# 0-1범위 내의 정규분포를 따르는 랜덤값을 가져와서 생성
np.random.rand(5)

array([0.79806566, 0.59127474, 0.54067748, 0.93814278, 0.87119194])

In [31]:
np.random.rand(5,5)

array([[0.90129179, 0.12958945, 0.04384532, 0.91001395, 0.71108472],
       [0.20243483, 0.63743784, 0.86400835, 0.33124929, 0.90233039],
       [0.42212348, 0.5894941 , 0.26654233, 0.58135721, 0.29705965],
       [0.01094179, 0.98777804, 0.36560629, 0.77959624, 0.207692  ],
       [0.93384467, 0.46527461, 0.94377805, 0.77558483, 0.27712793]])

In [32]:
# 가우시안 표준 정규 분포 랜덤값을 가져와서 생성
np.random.rand(5)

array([0.71951869, 0.277481  , 0.6584526 , 0.95190848, 0.13721452])

In [33]:
np.random.rand(5,5)

array([[0.79066665, 0.16333685, 0.0595712 , 0.39834277, 0.36656995],
       [0.52862628, 0.0832886 , 0.5628296 , 0.45016143, 0.13758199],
       [0.71052374, 0.52523012, 0.09438966, 0.93676692, 0.1517645 ],
       [0.23803322, 0.86836404, 0.71866488, 0.7853769 , 0.26141007],
       [0.05810958, 0.46444358, 0.99972808, 0.08509577, 0.63552898]])

In [35]:
# 특정 범위 내서 랜덤 정수의 숫자를 가져와서 생성
np.random.randint(1,1000)

661

In [36]:
np.random.randint(0, 1000, 10)

array([316, 568, 903, 290,  61, 384, 323, 598, 918, 105])